### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by J0B10** [jadc/modpack-manifest-generator#1]
Hi there!  
Your modpack manifest generator is pretty usefull, I use it it to automatically create dev builds of my modpack [infinitydune](https://github.com/J0B10/infinitydune).

Now I'dd like to make some smaller changes to the script (like not requiring a input to exit, exception handling if forgesvc.net does not respond & automatically generating a modlist.)

Unfortunatly this would come with some legal uncertenty as you have not added a license to the project wich means basically all rights reserved.

So it would be great if you could add a open source license, maybe [MIT](https://choosealicense.com/licenses/mit/)?

IDK if you are familliar with licensing, if not check out https://choosealicense.com/.

**Comment by jadc** [comment]
You are lucky I checked my e-mail. I am surprised my tool still works.
Feel free to make any changes you wish. I'll change the license to MIT.

**Comment by jadc** [comment]
You are lucky I checked this e-mail. I am surprised my tool still works.
Feel free to make any changes you wish. I'll change the license to MIT.
